### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jrd2017** [yylou/frappe-apps#1]
Thank you for sharing.  Quick question, do you need to install the AdminLTE?  I'm trying to integrate Frappe/Erpnext with a custom bootstrap template.

**Comment by yylou** [comment]
> Thank you for sharing. Quick question, do you need to install the AdminLTE? I'm trying to integrate Frappe/Erpnext with a custom bootstrap template.

Nope! You could import the source files of AdminLTE and manually adjust the environment to integrate it into Frappe. However, we still need to install the dependency of npm modules/packages! Feel free to let me know if you have any further questions.
